### ISSUE TITLE
How to do with multiple components

### ISSUE THREAD

**Issue by DarioRega** [phatnguyenuit/learn-to-build-react-package#1]
Hello !

I've seen your guide and it's really awesome, ive customized a bit to be able to have storybook running and multiple components. However, i can't make my build output the components, i have only the csj and esm index files, as soon as i try to customize to have multiple components.

I saw here https://github.com/phatnguyenuit/learn-to-build-react-package/blob/master/packages/my-react-package/src/index.ts that you're exporting * from hello. this file is the main index file of the src folder, how do you handle the case with multiple components ? I've seen quite a lot of guides, and many people just show with 1 component...

I've tried this way:

```
  ├── src
  │   ├── assets
  │   ├── components
  │   │   ├── Atoms
  │   │   │   └── Button
  │   │   │       ├── Button.tsx - the react component
  │   │   │       ├── Button.scss - if any custom css need to be added
  │   │   │       ├── Button.stories.tsx - stories of the component
  │   │   │       ├── Button.cy.tsx - contains component testing or e2e
  │   │   │       ├── styled.ts - contains the styled component under the namespace
  │   │   │       └── index.ts - export { default } from "./Button"
  │   │   │
  │   │   └── index.ts - export { default as Button } from "./Atoms/Button"
  │   │
  │   └── index.ts - export * from "./components"
```
But in the end i don't have any component in my lib/ but the two index files

Would be really nice if you could give me your advice here please

**Comment by phatnguyenuit** [comment]
Hi @DarioRega,
Thank you for being interesting in my article and my repository as well!
Based on your above requirements, I think you want some specific imports like
```typescript
import { SomeComponent } from '@your-lib/SomeComponent '
```

With my current approach, the import statement will be
```typescript
import { SomeComponent } from '@my-lib'
```
Why?
=> Because all of the files are composed together into the bundled file named `index.js`

To achieve your advanced requirements, I think you should prepare a building script
And I have one place you can refer to get more real example: https://github.com/mui/material-ui
This package allows us to import in 2 ways:

1.  Import from the `global` package scope
```typescript
import { SomeComponent } from '@my-lib'
```

2. Import from the `submodule` scope
```typescript
import { SomeComponent } from '@my-lib/SomeComponent'
```

Happy codding,
Fast

**Comment by DarioRega** [comment]
I see ! Thanks a lot for your reply ! i will try that out, the second solution seems better in term of bundle size !
