### ISSUE TITLE
Why is `react` not a dependency?

### ISSUE THREAD

**Issue by PaulRBerg** [phatnguyenuit/learn-to-build-react-package#2]
Thanks for sharing this template and the [accompanying article](https://medium.com/weekly-webtips/how-to-build-a-react-library-with-typescript-d0f08a1f517e).

I was looking at your code and saw that you are importing React in the global scope:

https://github.com/phatnguyenuit/learn-to-build-react-package/blob/51dbfd99d40b0aaaa5a3ae194e19e9a273ed6813/packages/my-react-package/src/hello/index.tsx#L1

Because of this import, shouldn't react be listed as a dependency in package.json?

https://github.com/phatnguyenuit/learn-to-build-react-package/blob/51dbfd99d40b0aaaa5a3ae194e19e9a273ed6813/packages/my-react-package/package.json#L38-L40

I saw that react is a peer dependency, but is that enough?

Side note: would you like to enable [GitHub Discussions](https://docs.github.com/en/discussions/quickstart) in this repository? I would have created a discussion instead of a repo.

**Comment by phatnguyenuit** [comment]
Thanks, @PaulRBerg for your interest in my article and the example repository as well 👍 
Regarding your question, I did not add `react` as a `dependency` in the example `package` because of some reasons below:
- `react` is the main dependency for every single React app project
- `react` is described as a `peerDependency` is a common pattern for react library/package to say that we need `react` in the compiling stage of the React app not the building stage of the package/library
- With `peerDependency`, we can skip putting them in the built package/library, you can refer to https://github.com/phatnguyenuit/learn-to-build-react-package/blob/51dbfd99d40b0aaaa5a3ae194e19e9a273ed6813/packages/my-react-package/rollup.config.js#L20

-  With `peerDependency`, it can be installed if the react app does not have `react` installed

For the development stage of the react package/library, we still need to have `react` for referencing, code so I listed `react` as a workspace dependency, you check refer to https://github.com/phatnguyenuit/learn-to-build-react-package/blob/51dbfd99d40b0aaaa5a3ae194e19e9a273ed6813/package.json#L22

I hope this information can answer your question above.
If any further concerns, do not hesitate to reply to this thread

Happy coding!

**Comment by PaulRBerg** [comment]
Thanks a lot for the detailed answer, @phatnguyenuit!

> For the development stage of the react package/library, we still need to have react for referencing

Makes complete sense! This is what I was missing - `react` should be added in `devDependencies`, not in `dependencies`.

I've also seen [this StackOverflow answer](https://stackoverflow.com/a/30454133/3873510) in the meantime, which validates your explanation.

> If any further concerns, do not hesitate to reply to this thread

Thanks. It's all clear now.
